### ISSUE TITLE
Wrong symlinks

### ISSUE THREAD

**Issue by paulmaly-v** [RaidMax/osu-replace#5]
https://github.com/RaidMax/osu-replace/blob/master/Code/osu!/Beatmap.cs#L79
https://github.com/RaidMax/osu-replace/blob/master/Code/osu!/Beatmap.cs#L107

Here the variable ImagePath has a wrong value at least because actual symlinks point to e.g. such path: D:\games\osu!\Songs\1137679 goreshit - Songs Compilation_ Part 1\Songs\bg.jpg

But I think it must be D:\games\osu!\Songs\bg.jpg as bg.jpg is created there.

![image](https://user-images.githubusercontent.com/78684225/150123314-fca791aa-4af9-4947-a315-14547923171d.png)

**Comment by paulmaly-v** [comment]
I have found the following possible solution: if the user will change in config file osu!.username the variable BeatmapDirectory = Songs into absolute path (in my case BeatmapDirectory = D:\games\osu!\Songs), it will work perfectly.

**Comment by paulmaly-v** [comment]
And also .exe file must be in osu! directory

**Comment by RaidMax** [comment]
Resolved with latest version
