### ISSUE TITLE
0 Succeeded

### ISSUE THREAD

**Issue by UnknownNate** [RaidMax/osu-replace#6]
I've looked through the other issues listed and tried everything there. I have the .exe already in the osu! directory, I tried with it outside and still had the same issue. I have the osu! folder selected, but when I try to run the replacer (I've tried with both an image and just a color), it reads "[0] succeeded, [194] skipped folders, [0] without backgrounds" I also tried running it outside of the osu! folder and it just sits on idle and does nothing after clicking apply. 
I tried running with restore checked just to see and I got [238] succeeded, with 0s for the other 2. Not really sure what else to try here, I followed the readme exactly

**Comment by RaidMax** [comment]
Just to check you live tried running it as admin?

**Comment by UnknownNate** [comment]
Yes, I did

**Comment by naworm** [comment]
Nothing happens for me either, every clicks on Apply will allocate 8MB of RAM more to the program and do nothing.

![image](https://github.com/RaidMax/osu-replace/assets/48997616/89335bdc-ec47-4553-8c40-787e98476dc7)

**Comment by Ayymoss** [comment]
@Naworm I updated it to .NET 8. You can get the latest release https://github.com/RaidMax/osu-replace/releases/tag/2.0.0

**Comment by naworm** [comment]
It is working, thanks a lot
